<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE siop_document [
<!ELEMENT siop_document (levels , default_scenario , extra_scenario?)>
<!ELEMENT levels (level)+>
<!ELEMENT level EMPTY>
<!ATTLIST level
          id CDATA #REQUIRED
          temp CDATA #REQUIRED>
<!ELEMENT default_scenario (limiter)+>
<!ELEMENT limiter (sts_item* , table_item*)>
<!ATTLIST limiter
          name CDATA #REQUIRED
          type (STS|number|bool) #REQUIRED>
<!ELEMENT sts_item EMPTY>
<!ATTLIST sts_item
          pre CDATA #IMPLIED
          perc CDATA #IMPLIED
          trigger CDATA #REQUIRED
          release CDATA #REQUIRED
          min CDATA #IMPLIED
          max CDATA #IMPLIED
          duration CDATA #IMPLIED>
<!ELEMENT table_item EMPTY>
<!ATTLIST table_item
          temp CDATA #REQUIRED
          value CDATA #REQUIRED
          low_temp CDATA #IMPLIED>
<!ELEMENT extra_scenario (scenario)+>
<!ELEMENT scenario (trigger_statuses? , trigger_packages? , limiter*)>
<!ATTLIST scenario name CDATA #REQUIRED>
<!ATTLIST scenario priority CDATA #IMPLIED>
<!ELEMENT trigger_statuses (status)+>
<!ELEMENT status EMPTY>
<!ATTLIST status name CDATA #REQUIRED>
<!ELEMENT trigger_packages (package)+>
<!ELEMENT package EMPTY>
<!ATTLIST package name CDATA #REQUIRED>
] >

<siop_document>

    <levels>
        <level id="-1" temp="420" />
        <level id="0" temp="440" />
        <level id="1" temp="460" />
        <level id="2" temp="480" />
        <level id="3" temp="500" />
        <level id="4" temp="520" />
        <level id="5" temp="540" />
        <level id="6" temp="590" />
        <level id="7" temp="740" />
    </levels>

    <default_scenario>
        <limiter name="CPUFreqMax" type="number">
            <table_item temp="460" value="-1" />
            <table_item temp="480" value="1728000" />
            <table_item temp="500" value="1497600" />
            <table_item temp="520" value="1267200" />
            <table_item temp="540" value="1036800" />
        </limiter>
        <limiter name="CPUCoreMax" type="number">
            <table_item temp="440" value="-1" />
        </limiter>
        <limiter name="GPUFreqMax" type="number">
            <table_item temp="460" value="-1" />
            <table_item temp="480" value="389000000" />
            <table_item temp="500" value="320000000" />
            <table_item temp="520" value="200000000" />
            </limiter>
        <limiter name="LCDBrightness" type="number">
            <table_item temp="460" value="-1" />
            <table_item temp="500" value="219" />
        </limiter>
        <limiter name="Charging" type="number">
            <table_item temp="480" value="70" />
            <table_item temp="500" value="50" />
            <table_item temp="520" value="30" />
            <table_item temp="540" value="0" />
        </limiter>
        <limiter name="TempShift" type="number">
            <table_item temp="440" value="20" />
        </limiter>
        <limiter name="DynamicFpsLevel" type="number">
            <table_item temp="440" value="99" />
        </limiter>
        <limiter name="PST" type="number">
            <table_item temp="440" value="1" />
        </limiter>
        <limiter name="Flash" type="bool">
            <table_item temp="540" value="0" />
        </limiter>
        <limiter name="Recording" type="bool">
            <table_item temp="590" value="0" />
        </limiter>
        <limiter name="SmartBonding" type="bool">
            <table_item temp="500" value="0" />
        </limiter>
        <limiter name="CameraDisable" type="bool">
            <table_item temp="740" value="0" />
        </limiter>
    </default_scenario>

    <extra_scenario>

        <scenario name="HeavyUserScenario">
            <limiter name="CPUFreqMax" type="number">
                <table_item temp="520" value="-1" />
                <table_item temp="590" value="1036800" />
            </limiter>
            <limiter name="GPUFreqMax" type="number">
                <table_item temp="480" value="-1" />
                <table_item temp="520" value="462400000" />
                <table_item temp="540" value="389000000" />
                <table_item temp="590" value="320000000" />
            </limiter>
            <limiter name="TempShift" type="number">
                <table_item temp="440" value="0" />
            </limiter>
        </scenario>

        <scenario name="ShoppingMall">
            <trigger_packages>
                <package name="com.taobao.taobao" />
                <package name="com.tmall.wireless" />
                <package name="com.suning.mobile.ebuy" />
                <package name="com.tencent.mobileqq" />
                <package name="com.UCMobile" />
                <package name="com.tencent.mtt" />
            </trigger_packages>

            <limiter name="CPUFreqMax" type="number">
                <table_item temp="440" value="-1" />
                <table_item temp="480" value="1190400" />
                <table_item temp="540" value="1036800" />
            </limiter>
            <limiter name="GPUFreqMax" type="number">
                <table_item temp="440" value="-1" />
                <table_item temp="480" value="200000000" />
            </limiter>
        </scenario>

        <scenario name="CameraRecording">
            <trigger_statuses>
                <status name="Camera_recording" />
                <status name="Camera_recordingDual" />
                <status name="ChatOnV_vtCall" />
                <status name="Phone_vtCall" />
            </trigger_statuses>

            <limiter name="LCDBrightness" type="number">
                <table_item temp="440" value="182" />
                <table_item temp="460" value="134" />
            </limiter>
            <limiter name="TempShift" type="number">
                <table_item temp="440" value="30" />
            </limiter>
        </scenario>

        <scenario name="CameraShooting">
            <trigger_statuses>
                <status name="Camera_panoramaShot" />
                <status name="Camera_dramaShot" />
                <status name="Camera_burstShot" />
            </trigger_statuses>

            <limiter name="CPUFreqMax" type="number">
                <table_item temp="480" value="-1" />
                <table_item temp="500" value="1267200" />
                <table_item temp="590" value="1036800" />
            </limiter>
            <limiter name="GPUFreqMax" type="number">
                <table_item temp="480" value="-1" />
                <table_item temp="500" value="462400000" />
                <table_item temp="590" value="200000000" />
            </limiter>
        </scenario>

        <scenario name="ScreenOff">
            <limiter name="Charging" type="number">
                <table_item temp="440" value="100" />
            </limiter>
        </scenario>

        <scenario name="ScreenOffInCall">
            <limiter name="Charging" type="number">
                <table_item temp="440" value="70" />
            </limiter>
        </scenario>

        <scenario name="ScreenOnAppStarted">
            <limiter name="Charging" type="number">
                <table_item temp="440" value="30" />
            </limiter>
        </scenario>

        <scenario name="Hangouts">
            <trigger_packages>
                <package name="com.google.android.talk" />
            </trigger_packages>

            <limiter name="GPUFreqMax" type="number">
                <table_item temp="440" value="240000000" />
            </limiter>
        </scenario>

        <scenario name="HangoutsVTCall">
            <limiter name="CPUFreqMax" type="number">
                <table_item temp="440" value="-1" />
                <table_item temp="480" value="1190400" />
            </limiter>
            <limiter name="CPUCoreMax" type="number">
                <table_item temp="440" value="-1" />
                <table_item temp="480" value="2" />
            </limiter>
        </scenario>

        <scenario name="WatchNow">
            <trigger_packages>
                <package name="com.sec.android.app.videoplayer" />
            </trigger_packages>

            <limiter name="CPUFreqMax" type="number">
                <table_item temp="440" value="1574400" />
            </limiter>
        </scenario>

        <scenario name="ChatOnV">
            <trigger_statuses>
                <status name="ChatOnV_vtCall" />
            </trigger_statuses>

            <limiter name="LCDBrightness" type="number">
                <table_item temp="440" value="150" />
            </limiter>
        </scenario>

        <scenario name="MirroringBoost" priority="1">
            <trigger_statuses>
                <status name="ScreenMirroringBooster" />
            </trigger_statuses>

            <limiter name="CPUFreqMax" type="number">
                <table_item temp="440" value="-1" />
                <table_item temp="460" value="1267200" />
                <table_item temp="540" value="1036800" />
            </limiter>
            <limiter name="CPUCoreMax" type="number">
                <table_item temp="440" value="-1" />
                <table_item temp="460" value="2" />
            </limiter>
        </scenario>

        <scenario name="Navigation">
            <trigger_packages>
                <package name="com.baidu.BaiduMap" />
                <package name="com.google.android.apps.maps" />
                <package name="com.skt.skaf.l001mtm091" />
                <package name="kt.navi" />
                <package name="com.mnsoft.lgunavi" />
                <package name="com.locnall.KimGiSa" />
                <package name="kr.mappers.AtlanSmart" />
                <package name="com.mnsoft.mappyobn" />
                <package name="com.thinkware.inaviair" />
                <package name="com.thinkware.sundo.inavi3d" />
                <package name="net.daum.android.map" />
                <package name="com.nhn.android.nmap" />
                <package name="com.autonavi.minimap" />
            </trigger_packages>

            <limiter name="CPUFreqMax" type="number">
                <table_item temp="440" value="1267200" />
                <table_item temp="520" value="1036800" />
            </limiter>
            <limiter name="GPUFreqMax" type="number">
                <table_item temp="440" value="240000000" />
            </limiter>
            <limiter name="Charging" type="number">
                <table_item temp="440" value="30" />
                <table_item temp="540" value="0" />
            </limiter>
        </scenario>

        <scenario name="HotGameControl0">
            <trigger_packages>
                <package name="com.arbstudios.tikikartfree" />
            </trigger_packages>

            <limiter name="CPUFreqMax" type="number">
                <table_item temp="440" value="-1" />
                <table_item temp="480" value="1190400" />
                <table_item temp="540" value="1036800" />
            </limiter>
            <limiter name="DynamicFpsLevel" type="number">
                <table_item temp="440" value="60" />
            </limiter>
        </scenario>

        <scenario name="HotGameControl1">
            <trigger_packages>
                <package name="com.ea.games.r3_row" />
                <package name="com.ea.games.r3_na" />
                <package name="com.gameloft.android.ANMP.GloftIMHM" />
                <package name="com.gameloft.android.ANMP.GloftIAHM" />
                <package name="com.gameloft.android.ANMP.GloftMBHM" />
                <package name="com.experience_game_3d.truck.parking" />
                <package name="com.icloudzone.TruckPark3D" />
                <package name="com.fungames.truck.parking.bus" />
                <package name="com.androidromania.truckparking" />
                <package name="com.tapinator.truck.parking.bus3d" />
                <package name="com.Pulsar.ParkingTruck3D" />
                <package name="com.firetruckparking3d" />
                <package name="com.androidromania.eutruck" />
                <package name="air.TruckParkingMania" />
                <package name="com.madeleinesmithsi.truckparking" />
                <package name="pl.surix.parkingtruck" />
                <package name="com.bittales.truckparking" />
                <package name="www.chi.ParkingCar" />
                <package name="com.panosoft.parkingtruck" />
                <package name="com.panosoft.parkingtruckfree" />
                <package name="com.vg.truckparking" />
                <package name="com.mck.speedparking" />
                <package name="air.LearnersParking" />
                <package name="com.studio3wg.monstertruckparking" />
                <package name="com.timekiller.truckparking3D" />
                <package name="com.trifingger.truckpark" />
                <package name="com.anchorgame.truckparking2d" />
                <package name="com.palmple.koresbl.google" />
                <package name="com.patistudio.milc4kakao" />
                <package name="com.cjenm.monster" />
                <package name="com.cjenm.monster.nstore" />
                <package name="com.rovio.angrybirds" />
                <package name="com.imangi.templerun" />
                <package name="com.alphacloud.castlemaster" />
                <package name="com.studio7775.BeatMP3" />
                <package name="com.cjenm.boong" />
                <package name="com.ftt.suhoji_gl_4kakao" />
                <package name="com.bicore.groad" />
                <package name="com.gameloft.android.ANMP.GloftA6HP" />
                <package name="com.gameloft.android.GAND.GloftA6HP" />
                <package name="com.gameloft.android.ANMP.GloftA7HM" />
                <package name="com.gameloft.android.GAND.Gloft7ASS" />
                <package name="com.gameloft.android.ANMP.GloftA8HM" />
                <package name="GAND.GloftA" />
                <package name="ANMP.GloftA" />
                <package name="com.noknok.BEAUTYCITY" />
                <package name="me.pou.app" />
                <package name="com.glu.modwarsniper_91" />
                <package name="com.ea.games.nfs13_ro_lower" />
                <package name="com.glu.flcn_new" />
            </trigger_packages>

            <limiter name="CPUFreqMax" type="number">
                <table_item temp="440" value="-1" />
                <table_item temp="480" value="1190400" />
                <table_item temp="540" value="1036800" />
            </limiter>
            <limiter name="GPUFreqMax" type="number">
                <table_item temp="440" value="-1" />
                <table_item temp="480" value="200000000" />
            </limiter>
        </scenario>

        <scenario name="HotGameControl2">
            <trigger_packages>
                <package name="com.glu.gunbros2" />
                <package name="com.glu.robocop" />
                <package name="com.sega.sonicdash" />
                <package name="com.glu.ewarriors3" />
                <package name="com.socialquantum.acitykakao" />
                <package name="com.cjenm.heroes" />
                <package name="com.com2us.tinyfarm.normal.freefull.google.global.android.common" />
                <package name="com.ftt.soulblade_gl_4kakao" />
                <package name="com.ftt.soulblade_t_4kakao" />
            </trigger_packages>

            <limiter name="CPUFreqMax" type="number">
                <table_item temp="440" value="-1" />
                <table_item temp="480" value="1574400" />
                <table_item temp="520" value="1036800" />
            </limiter>
            <limiter name="GPUFreqMax" type="number">
                <table_item temp="440" value="-1" />
                <table_item temp="480" value="320000000" />
                <table_item temp="520" value="200000000" />
            </limiter>
            <limiter name="DynamicFpsLevel" type="number">
                <table_item temp="440" value="60" />
            </limiter>
        </scenario>

        <scenario name="HotGameControl3">
            <trigger_packages>
                <package name="com.ea.games.r3_row" />
                <package name="com.ea.games.r3_na" />
            </trigger_packages>

            <limiter name="CPUFreqMax" type="number">
                <table_item temp="440" value="-1" />
                <table_item temp="460" value="1036800" />
            </limiter>
            <limiter name="GPUFreqMax" type="number">
                <table_item temp="440" value="-1" />
                <table_item temp="460" value="200000000" />
            </limiter>
            <limiter name="PST" type="number">
                <table_item temp="440" value="0" />
                <table_item temp="460" value="1" />
            </limiter>
            <limiter name="TempShift" type="number">
                <table_item temp="440" value="0" />
                <table_item temp="460" value="50" />
            </limiter>
        </scenario>

        <scenario name="HotGameControl4">
            <trigger_packages>
                <package name="com.bestsolitaire.solitaire" />
                <package name="com.crescentmoongames.blocky_roads" />
                <package name="com.mck.trucksimulator" />
                <package name="com.ovilex.trucksimulator3d" />
                <package name="com.doyeon.FpsDefence" />
                <package name="com.kiloo.subwaysurf" />
                <package name="com.pnixgames.wintersports" />
                <package name="pl.macaque.hangmanpl" />
                <package name="com.disney.wheresmywater2_goo" />
                <package name="com.midasplayer.apps.papapearsaga" />
                <package name="com.chi.Boat" />
                <package name="com.perplelab.sampl4kakao" />
            </trigger_packages>

            <limiter name="CPUFreqMax" type="number">
                <table_item temp="440" value="-1" />
                <table_item temp="480" value="1036800" />
            </limiter>
            <limiter name="GPUFreqMax" type="number">
                <table_item temp="440" value="-1" />
                <table_item temp="480" value="200000000" />
            </limiter>
        </scenario>

        <scenario name="TPBoost">
            <trigger_packages>
                <package name="com.FTATS" />
            </trigger_packages>

            <limiter name="CPUFreqMax" type="number">
                <table_item temp="440" value="-1" />
            </limiter>
        </scenario>

        <scenario name="AppStart" priority="1">
            <limiter name="CPUFreqMax" type="number">
                <table_item temp="440" value="-1" />
            </limiter>
            <limiter name="GPUFreqMax" type="number">
                <table_item temp="440" value="-1" />
            </limiter>
        </scenario>

    </extra_scenario>

</siop_document>
