<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE siop_document [
<!ELEMENT siop_document (levels , default_scenario , extra_scenario?)>
<!ELEMENT levels (level)+>
<!ELEMENT level EMPTY>
<!ATTLIST level
          id CDATA #REQUIRED
          temp CDATA #REQUIRED>
<!ELEMENT default_scenario (limiter)+>
<!ELEMENT limiter (sts_item* , table_item*)>
<!ATTLIST limiter
          name CDATA #REQUIRED
          type (STS|number|bool) #REQUIRED>
<!ELEMENT sts_item EMPTY>
<!ATTLIST sts_item
          pre CDATA #IMPLIED
          perc CDATA #IMPLIED
          trigger CDATA #REQUIRED
          release CDATA #REQUIRED
          min CDATA #IMPLIED
          max CDATA #IMPLIED
          duration CDATA #IMPLIED>
<!ELEMENT table_item EMPTY>
<!ATTLIST table_item
          temp CDATA #REQUIRED
          value CDATA #REQUIRED
          low_temp CDATA #IMPLIED>
<!ELEMENT extra_scenario (scenario)+>
<!ELEMENT scenario (trigger_statuses? , trigger_packages? , limiter*)>
<!ATTLIST scenario name CDATA #REQUIRED>
<!ATTLIST scenario priority CDATA #IMPLIED>
<!ELEMENT trigger_statuses (status)+>
<!ELEMENT status EMPTY>
<!ATTLIST status name CDATA #REQUIRED>
<!ELEMENT trigger_packages (package)+>
<!ELEMENT package EMPTY>
<!ATTLIST package name CDATA #REQUIRED>
] >

<siop_document>

    <levels>
        <level id="0" temp="430" />
        <level id="1" temp="450" />
        <level id="2" temp="470" />
        <level id="3" temp="490" />
        <level id="4" temp="510" />
        <level id="5" temp="530" />
        <level id="6" temp="610" />
    </levels>

    <default_scenario>
        <limiter name="CPUFreqMax" type="number">
            <table_item temp="450" value="-1" />
            <table_item temp="470" value="998400" />
            <table_item temp="510" value="998400" />
            <table_item temp="530" value="800000" />
        </limiter>
        <limiter name="CPUCoreMax" type="number">
            <table_item temp="430" value="-1" />
        </limiter>
        <limiter name="GPUFreqMax" type="number">
            <table_item temp="470" value="-1" />
            <table_item temp="490" value="310000000" />
        </limiter>
        <limiter name="PST" type="number">
            <table_item temp="430" value="0" />
        </limiter>
        <limiter name="Charging" type="number">
            <table_item temp="430" value="50" />
        </limiter>
        <limiter name="LCDBrightness" type="number">
            <table_item temp="470" value="-1" />
            <table_item temp="490" value="227" />
        </limiter>
        <limiter name="SmartBonding" type="bool">
            <table_item temp="490" value="0" />
        </limiter>
    </default_scenario>

    <extra_scenario>

        <scenario name="CameraRecording">
            <trigger_statuses>
                <status name="Camera_recording" />
                <status name="Camera_recordingDual" />
                <status name="Phone_vtCall" />
            </trigger_statuses>

            <limiter name="CPUFreqMax" type="number">
                <table_item temp="380" value="-1" />
                <table_item temp="410" value="800000" />
            </limiter>
        </scenario>

        <scenario name="VTCall">
            <trigger_statuses>
                <status name="Phone_vtCall" />
            </trigger_statuses>

            <limiter name="Charging" type="number">
                <table_item temp="410" value="30" />
            </limiter>
        </scenario>

        <scenario name="ScreenOff">
            <limiter name="Charging" type="number">
                <table_item temp="410" value="100" />
            </limiter>
        </scenario>

        <scenario name="ScreenOffInCall">
            <limiter name="Charging" type="number">
                <table_item temp="410" value="40" />
            </limiter>
        </scenario>

        <scenario name="ScreenOnAppStarted">
            <limiter name="Charging" type="number">
                <table_item temp="410" value="30" />
            </limiter>
        </scenario>

        <scenario name="BrowserMode">
            <trigger_packages>
                <package name="com.sec.android.app.sbrowser" />
                <package name="com.android.browser" />
                <package name="com.android.chrome" />
                <package name="com.android.email" />
            </trigger_packages>

            <limiter name="Charging" type="number">
                <table_item temp="410" value="40" />
            </limiter>
        </scenario>

        <scenario name="Hangouts">
            <trigger_packages>
                <package name="com.google.android.talk" />
            </trigger_packages>

            <limiter name="GPUFreqMax" type="number">
                <table_item temp="380" value="-1" />
                <table_item temp="410" value="200000000" />
            </limiter>
        </scenario>

        <scenario name="HangoutsVTCall">
            <limiter name="CPUFreqMax" type="number">
                <table_item temp="380" value="-1" />
                <table_item temp="410" value="800000" />
            </limiter>
            <limiter name="CPUCoreMax" type="number">
                <table_item temp="380" value="-1" />
                <table_item temp="410" value="2" />
            </limiter>
            <limiter name="Charging" type="number">
                <table_item temp="380" value="100" />
                <table_item temp="410" value="50" />
                <table_item temp="430" value="40" />
                <table_item temp="450" value="30" />
            </limiter>
        </scenario>

        <scenario name="HotGameControl3">
            <trigger_packages>
                <package name="com.ea.games.r3_row" />
                <package name="com.ea.games.r3_na" />
            </trigger_packages>

            <limiter name="CPUFreqMax" type="number">
                <table_item temp="380" value="-1" />
                <table_item temp="400" value="998400" />
                <table_item temp="420" value="800000" />
            </limiter>
            <limiter name="GPUFreqMax" type="number">
                <table_item temp="380" value="-1" />
                <table_item temp="400" value="310000000" />
            </limiter>
            <limiter name="Charging" type="number">
                <table_item temp="380" value="50" />
            </limiter>
        </scenario>

        <scenario name="HotGameControlException">
            <trigger_packages>
                <package name="com.nhnent.SKCOOKIEPANG" />
                <package name="com.ftt.soulblade_t_4kakao" />
                <package name="com.ftt.soulblade_gl_4kakao" />
                <package name="com.sq.dragonsworld.kakao" />
            </trigger_packages>

            <limiter name="CPUFreqMax" type="number">
                <table_item temp="380" value="-1" />
                <table_item temp="410" value="998400" />
                <table_item temp="430" value="800000" />
            </limiter>
            <limiter name="GPUFreqMax" type="number">
                <table_item temp="380" value="-1" />
                <table_item temp="410" value="310000000" />
                <table_item temp="490" value="310000000" />
                <table_item temp="510" value="200000000" />
            </limiter>
            <limiter name="Charging" type="number">
                <table_item temp="380" value="100" />
                <table_item temp="410" value="50" />
                <table_item temp="430" value="50" />
                <table_item temp="450" value="40" />
            </limiter>
        </scenario>

        <scenario name="AppStart" priority="1">
            <limiter name="CPUFreqMax" type="number">
                <table_item temp="410" value="-1" />
            </limiter>
            <limiter name="GPUFreqMax" type="number">
                <table_item temp="410" value="-1" />
            </limiter>
        </scenario>

    </extra_scenario>

</siop_document>
