<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE siop_document [
<!ELEMENT siop_document (levels , default_scenario , extra_scenario?)>
<!ELEMENT levels (level)+>
<!ELEMENT level EMPTY>
<!ATTLIST level
          id CDATA #REQUIRED
          temp CDATA #REQUIRED>
<!ELEMENT default_scenario (limiter)+>
<!ELEMENT limiter (sts_item* , table_item*)>
<!ATTLIST limiter
          name CDATA #REQUIRED
          type (STS|number|bool) #REQUIRED>
<!ELEMENT sts_item EMPTY>
<!ATTLIST sts_item
          pre CDATA #IMPLIED
          perc CDATA #IMPLIED
          trigger CDATA #REQUIRED
          release CDATA #REQUIRED
          min CDATA #IMPLIED
          max CDATA #IMPLIED
          duration CDATA #IMPLIED>
<!ELEMENT table_item EMPTY>
<!ATTLIST table_item
          temp CDATA #REQUIRED
          value CDATA #REQUIRED
          low_temp CDATA #IMPLIED>
<!ELEMENT extra_scenario (scenario)+>
<!ELEMENT scenario (trigger_statuses? , trigger_packages? , limiter*)>
<!ATTLIST scenario name CDATA #REQUIRED>
<!ATTLIST scenario priority CDATA #IMPLIED>
<!ELEMENT trigger_statuses (status)+>
<!ELEMENT status EMPTY>
<!ATTLIST status name CDATA #REQUIRED>
<!ELEMENT trigger_packages (package)+>
<!ELEMENT package EMPTY>
<!ATTLIST package name CDATA #REQUIRED>
] >

<siop_document>

    <levels>
        <level id="0" temp="400" />
        <level id="1" temp="420" />
        <level id="2" temp="450" />
        <level id="3" temp="480" />
        <level id="4" temp="500" />
        <level id="5" temp="520" />
    </levels>

    <default_scenario>
        <limiter name="CPUFreqMax" type="number">
            <table_item temp="420" value="-1" />
            <table_item temp="450" value="1500000" />
            <table_item temp="480" value="1200000" />
            <table_item temp="500" value="1000000" />
            <table_item temp="520" value="800000" />
        </limiter>
        <limiter name="CPUCoreMax" type="number">
            <table_item temp="400" value="-1" />
        </limiter>
        <limiter name="GPUFreqMax" type="number">
            <table_item temp="420" value="-1" />
            <table_item temp="450" value="450" />
            <table_item temp="480" value="450" />
            <table_item temp="500" value="350" />
            <table_item temp="520" value="266" />
            </limiter>
        <limiter name="LCDBrightness" type="number">
            <table_item temp="450" value="-1" />
            <table_item temp="480" value="248" />
        </limiter>
        <limiter name="Charging" type="number">
            <table_item temp="450" value="70" />
            <table_item temp="480" value="50" />
            <table_item temp="500" value="30" />
        </limiter>
        <limiter name="Flash" type="bool">
            <table_item temp="520" value="0" />
        </limiter>
        <limiter name="SmartBonding" type="bool">
            <table_item temp="480" value="0" />
        </limiter>
    </default_scenario>

    <extra_scenario>

        <scenario name="CameraRecording">
            <trigger_statuses>
                <status name="Camera_recording" />
                <status name="Camera_recordingDual" />
                <status name="ChatOnV_vtCall" />
                <status name="Phone_vtCall" />
            </trigger_statuses>

            <limiter name="LCDBrightness" type="number">
                <table_item temp="400" value="-1" />
                <table_item temp="420" value="241" />
                <table_item temp="450" value="200" />
                <table_item temp="500" value="150" />
            </limiter>
        </scenario>

        <scenario name="HotGameControl1">
            <trigger_packages>
                <package name="com.ea.games.r3_row" />
                <package name="com.ea.games.r3_na" />
                <package name="com.gameloft.android.ANMP.GloftIMHM" />
                <package name="com.gameloft.android.ANMP.GloftIAHM" />
                <package name="com.gameloft.android.ANMP.GloftMBHM" />
                <package name="com.experience_game_3d.truck.parking" />
                <package name="com.icloudzone.TruckPark3D" />
                <package name="com.fungames.truck.parking.bus" />
                <package name="com.androidromania.truckparking" />
                <package name="com.tapinator.truck.parking.bus3d" />
                <package name="com.Pulsar.ParkingTruck3D" />
                <package name="com.firetruckparking3d" />
                <package name="com.androidromania.eutruck" />
                <package name="air.TruckParkingMania" />
                <package name="com.madeleinesmithsi.truckparking" />
                <package name="pl.surix.parkingtruck" />
                <package name="com.bittales.truckparking" />
                <package name="www.chi.ParkingCar" />
                <package name="com.panosoft.parkingtruck" />
                <package name="com.panosoft.parkingtruckfree" />
                <package name="com.vg.truckparking" />
                <package name="com.mck.speedparking" />
                <package name="air.LearnersParking" />
                <package name="com.studio3wg.monstertruckparking" />
                <package name="com.timekiller.truckparking3D" />
                <package name="com.trifingger.truckpark" />
                <package name="com.anchorgame.truckparking2d" />
                <package name="com.palmple.koresbl.google" />
                <package name="com.patistudio.milc4kakao" />
                <package name="com.cjenm.monster" />
                <package name="com.cjenm.monster.nstore" />
                <package name="com.rovio.angrybirds" />
                <package name="com.imangi.templerun" />
                <package name="com.alphacloud.castlemaster" />
                <package name="com.studio7775.BeatMP3" />
                <package name="com.cjenm.boong" />
                <package name="com.ftt.suhoji_gl_4kakao" />
                <package name="com.bicore.groad" />
                <package name="com.gameloft.android.ANMP.GloftA6HP" />
                <package name="com.gameloft.android.GAND.GloftA6HP" />
                <package name="com.gameloft.android.ANMP.GloftA7HM" />
                <package name="com.gameloft.android.GAND.Gloft7ASS" />
                <package name="com.gameloft.android.ANMP.GloftA8HM" />
                <package name="GAND.GloftA" />
                <package name="ANMP.GloftA" />
                <package name="com.noknok.BEAUTYCITY" />
                <package name="me.pou.app" />
                <package name="com.glu.modwarsniper_91" />
                <package name="com.ea.games.nfs13_ro_lower" />
                <package name="com.glu.flcn_new" />
            </trigger_packages>

            <limiter name="CPUFreqMax" type="number">
                <table_item temp="400" value="-1" />
                <table_item temp="420" value="1000000" />
                <table_item temp="500" value="1000000" />
                <table_item temp="520" value="800000" />
            </limiter>
            <limiter name="GPUFreqMax" type="number">
                <table_item temp="400" value="-1" />
                <table_item temp="420" value="266" />
            </limiter>
        </scenario>

        <scenario name="ScreenOff">
            <limiter name="Charging" type="number">
                <table_item temp="400" value="100" />
            </limiter>
        </scenario>

        <scenario name="ScreenOffInCall">
            <limiter name="Charging" type="number">
                <table_item temp="400" value="70" />
            </limiter>
        </scenario>

        <scenario name="ScreenOnAppStarted">
            <limiter name="Charging" type="number">
                <table_item temp="400" value="30" />
            </limiter>
        </scenario>

        <scenario name="AppStart" priority="1">
            <limiter name="CPUFreqMax" type="number">
                <table_item temp="400" value="-1" />
            </limiter>
            <limiter name="GPUFreqMax" type="number">
                <table_item temp="400" value="-1" />
            </limiter>
        </scenario>

    </extra_scenario>

</siop_document>
