<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE siop_document [
<!ELEMENT siop_document (levels , default_scenario , extra_scenario?)>
<!ELEMENT levels (level)+>
<!ELEMENT level EMPTY>
<!ATTLIST level
          id CDATA #REQUIRED
          temp CDATA #REQUIRED>
<!ELEMENT default_scenario (limiter)+>
<!ELEMENT limiter (sts_item* , table_item*)>
<!ATTLIST limiter
          name CDATA #REQUIRED
          type (STS|number|bool) #REQUIRED>
<!ELEMENT sts_item EMPTY>
<!ATTLIST sts_item
          pre CDATA #IMPLIED
          perc CDATA #IMPLIED
          trigger CDATA #REQUIRED
          release CDATA #REQUIRED
          min CDATA #IMPLIED
          max CDATA #IMPLIED
          duration CDATA #IMPLIED>
<!ELEMENT table_item EMPTY>
<!ATTLIST table_item
          temp CDATA #REQUIRED
          value CDATA #REQUIRED
          low_temp CDATA #IMPLIED>
<!ELEMENT extra_scenario (scenario)+>
<!ELEMENT scenario (trigger_statuses? , trigger_packages? , limiter*)>
<!ATTLIST scenario name CDATA #REQUIRED>
<!ATTLIST scenario priority CDATA #IMPLIED>
<!ELEMENT trigger_statuses (status)+>
<!ELEMENT status EMPTY>
<!ATTLIST status name CDATA #REQUIRED>
<!ELEMENT trigger_packages (package)+>
<!ELEMENT package EMPTY>
<!ATTLIST package name CDATA #REQUIRED>
] >

<siop_document>

    <levels>
        <level id="0" temp="430" />
        <level id="1" temp="450" />
        <level id="2" temp="470" />
        <level id="3" temp="490" />
        <level id="4" temp="510" />
        <level id="5" temp="530" />
    </levels>

    <default_scenario>
        <limiter name="CPUFreqMax" type="number">
            <table_item temp="450" value="-1" />
            <table_item temp="470" value="1344000" />
            <table_item temp="490" value="1344000" />
            <table_item temp="510" value="1113600" />
            <table_item temp="530" value="499200" />
        </limiter>
        <limiter name="CPUCoreMax" type="number">
            <table_item temp="430" value="-1" />
        </limiter>
        <limiter name="GPUFreqMax" type="number">
            <table_item temp="520" value="-1" />
            <table_item temp="540" value="400000000" />
        </limiter>
        <limiter name="TempShift" type="number">
            <table_item temp="430" value="0" />
        </limiter>
        <limiter name="PST" type="number">
            <table_item temp="430" value="1" />
        </limiter>
        <limiter name="Charging" type="number">
            <table_item temp="430" value="70" />
        </limiter>
        <limiter name="LCDBrightness" type="number">
            <table_item temp="520" value="-1" />
            <table_item temp="540" value="219" />
        </limiter>
        <limiter name="DynamicFpsLevel" type="number">
            <table_item temp="430" value="99" />
        </limiter>
        <limiter name="SmartBonding" type="bool">
            <table_item temp="490" value="0" />
        </limiter>
    </default_scenario>

    <extra_scenario>

        <scenario name="ScreenOff">
            <limiter name="Charging" type="number">
                <table_item temp="430" value="100" />
            </limiter>
        </scenario>

        <scenario name="ScreenOffInCall">
            <limiter name="Charging" type="number">
                <table_item temp="430" value="45" />
            </limiter>
        </scenario>

        <scenario name="ScreenOnAppStarted">
            <limiter name="Charging" type="number">
                <table_item temp="430" value="30" />
            </limiter>
        </scenario>

        <scenario name="CameraRecording">
            <trigger_statuses>
                <status name="Camera_recording" />
                <status name="Camera_recordingDual" />
                <status name="ChatOnV_vtCall" />
                <status name="Phone_vtCall" />
            </trigger_statuses>

            <limiter name="CPUFreqMax" type="number">
                <table_item temp="400" value="-1" />
                <table_item temp="420" value="400000" />
            </limiter>
        </scenario>

        <scenario name="CameraShooting">
            <trigger_statuses>
                <status name="Camera_burstShot" />
            </trigger_statuses>

            <limiter name="CPUFreqMax" type="number">
                <table_item temp="400" value="-1" />
            </limiter>
            <limiter name="GPUFreqMax" type="number">
                <table_item temp="400" value="-1" />
            </limiter>
        </scenario>

        <scenario name="BrowserMode">
            <trigger_packages>
                <package name="com.sec.android.app.sbrowser" />
                <package name="com.android.browser" />
                <package name="com.android.chrome" />
                <package name="com.android.email" />
            </trigger_packages>

            <limiter name="Charging" type="number">
                <table_item temp="430" value="55" />
            </limiter>
        </scenario>

        <scenario name="ShoppingMall">
            <trigger_packages>
                <package name="com.taobao.taobao" />
                <package name="com.tmall.wireless" />
                <package name="com.suning.mobile.ebuy" />
                <package name="com.tencent.mobileqq" />
                <package name="com.UCMobile" />
                <package name="com.tencent.mtt" />
            </trigger_packages>

            <limiter name="CPUFreqMax" type="number">
                <table_item temp="410" value="-1" />
                <table_item temp="430" value="1036800" />
                <table_item temp="480" value="556800" />
            </limiter>
            <limiter name="GPUFreqMax" type="number">
                <table_item temp="410" value="-1" />
                <table_item temp="430" value="400000000" />
                <table_item temp="480" value="220000000" />
            </limiter>
            <limiter name="Charging" type="number">
                <table_item temp="430" value="55" />
            </limiter>
        </scenario>

        <scenario name="Hangouts">
            <trigger_packages>
                <package name="com.google.android.talk" />
                <package name="com.tencent.mm" />
                <package name="com.tencent.mobileqq" />
            </trigger_packages>

            <limiter name="GPUFreqMax" type="number">
                <table_item temp="430" value="400000000" />
            </limiter>
        </scenario>

        <scenario name="HangoutsVTCall">
            <limiter name="CPUFreqMax" type="number">
                <table_item temp="430" value="400000" />
            </limiter>
            <limiter name="CPUCoreMax" type="number">
                <table_item temp="430" value="1" />
            </limiter>
        </scenario>

        <scenario name="HotGameControl3">
            <trigger_packages>
                <package name="com.ea.games.r3_row" />
                <package name="com.ea.games.r3_na" />
            </trigger_packages>

            <limiter name="CPUFreqMax" type="number">
                <table_item temp="400" value="-1" />
                <table_item temp="420" value="1036800" />
            </limiter>
            <limiter name="GPUFreqMax" type="number">
                <table_item temp="440" value="-1" />
                <table_item temp="460" value="400000000" />
            </limiter>
            <limiter name="Charging" type="number">
                <table_item temp="420" value="100" />
                <table_item temp="440" value="60" />
                <table_item temp="460" value="55" />
                <table_item temp="470" value="50" />
            </limiter>
            <limiter name="PST" type="number">
                <table_item temp="420" value="0" />
            </limiter>
        </scenario>

        <scenario name="HotGameControlExtreme0">
            <trigger_packages>
                <package name="com.netmarble.mpoker" />
                <package name="com.efun.kr.hycs.google.obt" />
                <package name="com.efun.kr.hycs.naver.obt" />
                <package name="com.gggg.ggggbigfisherman" />
                <package name="com.fgol.HungrySharkEvolution" />
                <package name="com.disney.maleficent_goo" />
                <package name="com.wizardgames.crossyheroes" />
                <package name="com.cjenm.ma92014atv" />
                <package name="com.cjenm.ma92013.google" />
                <package name="com.kakaogame.ma92013" />
                <package name="com.sq.dragonsworld.kakao" />
                <package name="com.theonegames.gunshipbattle" />
                <package name="com.glu.dino" />
                <package name="com.dino.simulator.pro" />
                <package name="com.crocodile.simulator.free" />
                <package name="com.crocodile.simulator.pro" />
                <package name="com.machinezone.gow" />
                <package name="com.ahzs.hggoogle" />
                <package name="com.kakaogame.aura" />
                <package name="com.royai.shadowfight" />
                <package name="com.panda8.ghostghost" />
                <package name="com.cyougame.gedousanguo.korea.googleplay" />
                <package name="com.cjenm.heroes" />
                <package name="com.cjenm.sknights" />
                <package name="com.kakaogame.sknights" />
                <package name="air.com.tencent.qqpasture" />
                <package name="com.supercell.clashofclans" />
                <package name="com.yinhan.shenmo.duoku" />
                <package name="com.hugenstar.tdzmclient.DK" />
                <package name="com.qdazzle.shushan.DK" />
                <package name="com.com2us.tinyfarm.normal2.freefull.google.global.android.common" />
                <package name="com.gameloft.android.ANMP.GloftM4HM" />
                <package name="com.NextFloor.ElBrisaKakao" />
                <package name="com.tactel.electopia" />
            </trigger_packages>

            <limiter name="CPUFreqMax" type="number">
                <table_item temp="400" value="-1" />
                <table_item temp="420" value="556800" />
            </limiter>
            <limiter name="GPUFreqMax" type="number">
                <table_item temp="420" value="-1" />
                <table_item temp="440" value="220000000" />
            </limiter>
            <limiter name="Charging" type="number">
                <table_item temp="420" value="100" />
                <table_item temp="440" value="60" />
                <table_item temp="460" value="55" />
                <table_item temp="470" value="50" />
            </limiter>
            <limiter name="PST" type="number">
                <table_item temp="420" value="0" />
            </limiter>
        </scenario>

        <scenario name="HotGameControlExtreme2">
            <trigger_packages>
                <package name="com.ftt.soulblade_gl_4kakao" />
                <package name="com.ftt.soulblade_t_4kakao" />
                <package name="com.sq.dragonsworld.kakao" />
                <package name="com.aim.racing" />
                <package name="com.wb.goog.mkx" />
                <package name="com.ludia.jurassicworld" />
                <package name="com.mgc.miami.crime.simulator" />
            </trigger_packages>

            <limiter name="CPUFreqMax" type="number">
                <table_item temp="400" value="-1" />
                <table_item temp="420" value="400000" />
            </limiter>
            <limiter name="GPUFreqMax" type="number">
                <table_item temp="420" value="-1" />
                <table_item temp="440" value="400000000" />
            </limiter>
            <limiter name="Charging" type="number">
                <table_item temp="420" value="100" />
                <table_item temp="440" value="60" />
                <table_item temp="460" value="55" />
                <table_item temp="470" value="50" />
            </limiter>
            <limiter name="PST" type="number">
                <table_item temp="420" value="0" />
            </limiter>
        </scenario>

        <scenario name="HotGameControlForChina0">
            <limiter name="CPUFreqMax" type="number">
                <table_item temp="400" value="-1" />
                <table_item temp="420" value="556800" />
            </limiter>
            <limiter name="GPUFreqMax" type="number">
                <table_item temp="420" value="-1" />
                <table_item temp="440" value="220000000" />
            </limiter>
            <limiter name="Charging" type="number">
                <table_item temp="420" value="100" />
                <table_item temp="440" value="60" />
                <table_item temp="460" value="55" />
                <table_item temp="470" value="50" />
            </limiter>
            <limiter name="PST" type="number">
                <table_item temp="420" value="0" />
            </limiter>
        </scenario>

        <scenario name="HotGameControlException">
            <trigger_packages>
                <package name="com.cjenm.sknights" />
            </trigger_packages>
            <limiter name="CPUFreqMax" type="number">
                <table_item temp="400" value="-1" />
                <table_item temp="420" value="556800" />
            </limiter>
            <limiter name="GPUFreqMax" type="number">
                <table_item temp="420" value="-1" />
                <table_item temp="440" value="400000000" />
            </limiter>
            <limiter name="Charging" type="number">
                <table_item temp="420" value="100" />
                <table_item temp="440" value="60" />
                <table_item temp="460" value="55" />
                <table_item temp="470" value="50" />
            </limiter>
            <limiter name="PST" type="number">
                <table_item temp="420" value="0" />
            </limiter>
        </scenario>

        <scenario name="DssGameControl">
            <limiter name="CPUFreqMax" type="number">
                <table_item temp="400" value="-1" />
                <table_item temp="420" value="556800" />
            </limiter>
            <limiter name="GPUFreqMax" type="number">
                <table_item temp="420" value="-1" />
                <table_item temp="440" value="220000000" />
            </limiter>
            <limiter name="Charging" type="number">
                <table_item temp="420" value="100" />
                <table_item temp="440" value="60" />
                <table_item temp="460" value="55" />
                <table_item temp="470" value="50" />
            </limiter>
            <limiter name="PST" type="number">
                <table_item temp="420" value="0" />
            </limiter>
        </scenario>

        <scenario name="MirroringBoost" priority="1">
            <trigger_statuses>
                <status name="ScreenMirroringBooster" />
            </trigger_statuses>

            <limiter name="CPUFreqMax" type="number">
                <table_item temp="400" value="556800" />
                <table_item temp="420" value="400000" />
            </limiter>
        </scenario>

        <scenario name="NDrive">
            <limiter name="CPUFreqMax" type="number">
                <table_item temp="360" value="-1" />
                <table_item temp="380" value="400000" />
            </limiter>
        </scenario>

        <scenario name="PreloadInstaller">
            <trigger_packages>
                <package name="com.sec.android.preloadinstaller" />
            </trigger_packages>
            <limiter name="CPUFreqMax" type="number">
                <table_item temp="430" value="1036800" />
            </limiter>
        </scenario>

        <scenario name="RetailMode">
            <trigger_packages>
                <package name="kr.co.rightbrain.RetailMode.A8_CN" />
            </trigger_packages>
            <limiter name="Charging" type="number">
                <table_item temp="430" value="40" />
            </limiter>
        </scenario>

        <scenario name="LowTemp" priority="2">
            <limiter name="CPUFreqMax" type="number">
                <table_item temp="-50" value="249600" />
                <table_item temp="-40" value="-1" />
            </limiter>
            <limiter name="GPUFreqMax" type="number">
                <table_item temp="-50" value="220000000" />
                <table_item temp="-40" value="-1" />
            </limiter>
            <limiter name="LCDBrightness" type="number">
                <table_item temp="-50" value="180" />
                <table_item temp="-40" value="-1" />
            </limiter>
        </scenario>

        <scenario name="AppStart" priority="1">
            <limiter name="CPUFreqMax" type="number">
                <table_item temp="430" value="-1" />
            </limiter>
            <limiter name="GPUFreqMax" type="number">
                <table_item temp="430" value="-1" />
            </limiter>
        </scenario>

        <scenario name="Navigation">
            <trigger_packages>
                <package name="com.baidu.BaiduMap" />
                <package name="com.google.android.apps.maps" />
                <package name="com.skt.skaf.l001mtm091" />
                <package name="kt.navi" />
                <package name="com.mnsoft.lgunavi" />
                <package name="com.locnall.KimGiSa" />
                <package name="kr.mappers.AtlanSmart" />
                <package name="com.mnsoft.mappyobn" />
                <package name="com.thinkware.inaviair" />
                <package name="com.thinkware.sundo.inavi3d" />
                <package name="net.daum.android.map" />
                <package name="com.nhn.android.nmap" />
                <package name="com.autonavi.minimap" />
            </trigger_packages>

            <limiter name="CPUFreqMax" type="number">
                <table_item temp="450" value="1344000" />
                <table_item temp="470" value="1036800" />
            </limiter>
            <limiter name="Charging" type="number">
                <table_item temp="450" value="50" />
                <table_item temp="470" value="45" />
                <table_item temp="490" value="40" />
            </limiter>
            <limiter name="DynamicFpsLevel" type="number">
                <table_item temp="430" value="99" />
                <table_item temp="450" value="66" />
                <table_item temp="470" value="33" />
            </limiter>
        </scenario>

        <scenario name="SoundCamp">
            <limiter name="CPUFreqMax" type="number">
                <table_item temp="430" value="556800" />
            </limiter>
        </scenario>

    </extra_scenario>

</siop_document>
